# Supabase Configuration
# Project: junielyfe
# Auth: Disabled (using Clerk)

project_id = "jwpopvvaoipjjslrlpmg"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false

[realtime]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = false

[storage]
enabled = true
file_size_limit = "5MB"

[auth]
enabled = false
# Clerk handles authentication
# Supabase Auth is disabled

[auth.email]
enable_signup = false

[edge_runtime]
enabled = false